### ISSUE TITLE
Mobius 5

### ISSUE THREAD

**Issue by ghpdohmen** [J-Waal/telecom#5]
There seems to be an error in the calculation of Rb for question 3
my data:
65 subcarriers
60 MHz transmission bandwidth
BPSK

**Comment by J-Waal** [comment]
I assume this is about problem 3b. The wrong variable was passed to the print statement. I made the same mistake.

**Comment by ghpdohmen** [comment]
DId you fix this in the commit "Fix issue"?

**Comment by J-Waal** [comment]
yes
